version: "3.8"

services:
  app:
    container_name: ${APP_NAME}
    build: ./
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    profiles:
      - postgres
    networks:
      - default

  postgres:
    container_name: ${DB_NAME}
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    profiles:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: notes
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

